jquery_lang_js.prototype.lang.el = {
	'Eye CheckApp':'Ευφυές Σύστημα Συμβουλευτικής Διάγνωσης',
	'Home':'Αρχική',
	'Symptom Checker':'Ευφυές σύστημα',
	'About':'Πληροφορίες',
	'Welcome':'Καλώς ήρθατε',
	"Eye CheckApp's Symptom checker helps you with your decision-making and health improvement efforts. Start now!":'Το παρόν εργαλείο σας παρέχει συμβουλευτική διάγνωση μέσω μίας σειράς απλών διαδοχικών ερωτήσεων.',
	'Start symptom checker':'Έναρξη συστήματος',
	'About':'Πληροφορίες',
	'Master Thesis of Spyridon-K. Dimopoulos':'Διπλωματική εργασία του Σπύρου Δημόπουλου',
	'Supervisor: Dr Ioannis K. Hatzilygeroudis':'Επιβλέπων καθηγητής: Ιωάννης Χατζηλυγερούδης',
	'Please select the area where you feel pain':'Παρακαλώ επιλέξτε το μέρος του σώματος στο οποίο εντοπίζετε το πρόβλημα',
	'select doctor in your area' : 'επιλογή ιατρού',
	'next' : 'συνέχεια',
	'You chose that you feel pain in the eyes':'Έχετε επιλέξει ότι το πρόβλημα εντοπίζετε στην περιοχή των ματιών',
	'To continue click next':'Για να συνεχίσετε πατήστε συνέχεια',
	'You chose that you feel pain in the chest':'Έχετε επιλέξει ότι το πρόβλημα εντοπίζετε στην περιοχή του θώρακα',
	'Results':'Αποτελέσματα:',
	'Doctors in your area':'Ιατροί στην περιοχή σας',
	'Doctor Details':'Λεπτομέρειες Ιατρού',
	'Send a message to the doctor containing the diagnosis from the expert system':'Στείλετε μήνυμα στον ιατρό με τη διάγνωση από το σύστημα',
	'Diagnosis from expert system:':'Η διάγνωση από το ευφυές σύστημα είναι:',
	'Send message':'Αποστολή μηνύματος',
	'Thank you for your message!':'Το μήνυμά σας στάλθηκε με επιτυχία'	                		
}